server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5   # 拉取服务时间
  instance:
    ip-address:  127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}  # eureka 服务的名字
zuul:
  prefix: /api
  retryable: true
  routes:
    item-service: /item/**   # item-service创建以后 、 添加路由规则
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
